spring:
  application:
    name: skyflow
    jwt:
      jwtSecret: xNsjrTXGsixTwuDycZxOqOMiFZpuznctbsbTULYbueULJKCpTD
      jwtRefreshSecret: IGmDcIIpXMIGkYtdlBbAmGCIgkNWMhvObaaPSkUXmrqBlKQQRX
      jwtExpirationMs: 86400000
      jwtRefreshTokenExpirationMs: 604800000

  datasource:
    url: jdbc:postgresql://localhost:5432/skyflow
    username: root
    password: ;(.314Luiv./
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
  servlet:
    context-path: /api